import { defineConfig, devices } from "@playwright/test";
import { resolve } from "path";

// Reserved E2E port — distinct from dev default (47831) to avoid collisions.
const E2E_PORT = 47890;

// Writable temp config generated by setup; lives in test-results/ (gitignored).
const E2E_CONFIG_PATH = resolve("test-results/portier-e2e-config.json");

export default defineConfig({
  testDir: "tests/e2e",
  // Run test files serially; tests within a file run serially too (no parallel workers).
  fullyParallel: false,
  workers: 1,
  timeout: 30_000,
  globalSetup: "./tests/e2e/helpers/setup.ts",
  reporter: process.env.CI ? "github" : [["html", { open: "never" }]],
  use: {
    baseURL: `http://127.0.0.1:${E2E_PORT}`,
    trace: "on-first-retry",
    screenshot: "only-on-failure",
    video: "on-first-retry",
  },
  projects: [
    {
      name: "chromium",
      use: { ...devices["Desktop Chrome"] },
    },
  ],
  webServer: {
    // Uses tsx (workspace devDep) to run the TypeScript server without a separate build step.
    // Requires client/build to exist — run `npm run build:client` first.
    command: `npx tsx server/sources/index.ts --host 127.0.0.1 --port ${E2E_PORT} --static-dir client/build`,
    env: {
      PORTIER_CONFIG: E2E_CONFIG_PATH,
    },
    url: `http://127.0.0.1:${E2E_PORT}/api/status`,
    reuseExistingServer: false,
    timeout: 30_000,
  },
});
