package activity

// Event type constants matching the TypeScript ActivityEventType union.
const (
	EventRuleCreated         = "rule.created"
	EventRuleUpdated         = "rule.updated"
	EventRuleDeleted         = "rule.deleted"
	EventRuleStarted         = "rule.started"
	EventRuleStopped         = "rule.stopped"
	EventRuleError           = "rule.error"
	EventTCPConnectionOpened = "tcp.connection.opened"
	EventTCPConnectionClosed = "tcp.connection.closed"
	EventTCPConnectionError  = "tcp.connection.error"
	EventUDPPacketForwarded  = "udp.packet.forwarded"
	EventUDPPacketReturned   = "udp.packet.returned"
	EventUDPPacketError      = "udp.packet.error"
	EventUDPSessionOpened    = "udp.session.opened"
	EventUDPSessionClosed    = "udp.session.closed"
	EventConfigExported      = "config.exported"
	EventConfigImported      = "config.imported"
	EventConfigImportFailed  = "config.import.failed"
)

// Severity constants matching the TypeScript ActivitySeverity union.
const (
	SeverityInfo    = "info"
	SeveritySuccess = "success"
	SeverityWarning = "warning"
	SeverityError   = "error"
)

// ActivityEvent is a single activity log entry. JSON field names match the TypeScript API contract.
type ActivityEvent struct {
	ID        string         `json:"id"`
	Timestamp string         `json:"timestamp"`
	Type      string         `json:"type"`
	Severity  string         `json:"severity"`
	RuleID    *string        `json:"ruleId,omitempty"`
	RuleName  *string        `json:"ruleName,omitempty"`
	Protocol  *string        `json:"protocol,omitempty"`
	Message   string         `json:"message"`
	Details   map[string]any `json:"details,omitempty"`
}

// ActivityEventInput is the input to Store.Add; ID and Timestamp are generated by the store.
type ActivityEventInput struct {
	Type     string
	Severity string
	RuleID   *string
	RuleName *string
	Protocol *string
	Message  string
	Details  map[string]any
}

// EventFunc is an optional callback for emitting activity events from forwarders.
type EventFunc func(input ActivityEventInput)
